version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
    timezone: America/Los_Angeles
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
